host: khemenu.thoth-station.ninja

managers:
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      maintainers:
        - sesheta
        - goern
        - fridex
        - gkrumbach07
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
