name: Deploy Stage

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Set Deployment Basename
        run: yarn run json -I -f package.json -e 'this.homepage="https://thoth-station.github.io/search-stage"'

      - name: Build
        run: yarn run build
        env:
          REACT_APP_DEPLOYMENT: "STAGE"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          repository-name: "thoth-station/search-stage"
